FROM rockylinux:9.3.20231119

ARG TIDB_VERSION=v7.5.2

VOLUME /tidb-data

RUN dnf -y update && dnf -y install glibc-langpack-en procps-ng psmisc mysql \
  && curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh \
  && /root/.tiup/bin/tiup install pd:${TIDB_VERSION} tidb:${TIDB_VERSION} tikv:${TIDB_VERSION} prometheus:${TIDB_VERSION} \
  && mkdir -p /root/.tiup/data \
  && ln -sf /tidb-data /root/.tiup/data/devenv

ENV PATH=/root/.tiup/bin:$PATH \
    TIDB_VERSION=${TIDB_VERSION}

EXPOSE 2379 3000 4000 9090 10080
